from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from mgm8.domain.models import OperationalEvent, ScheduledPass, SchedulingConflict


class ScheduledPassRepository(Protocol):
    def get_by_id(self, pass_id: UUID) -> ScheduledPass | None: ...
    def get_active_in_window(self, start: datetime, end: datetime) -> list[ScheduledPass]: ...
    def list_all(self) -> list[ScheduledPass]: ...
    def add(self, scheduled_pass: ScheduledPass) -> None: ...
    def update(self, scheduled_pass: ScheduledPass) -> None: ...


class SchedulingConflictRepository(Protocol):
    def add(self, conflict: SchedulingConflict) -> None: ...
    def list_recent(self, limit: int = 20) -> list[SchedulingConflict]: ...


class OperationalEventRepository(Protocol):
    def add(self, event: OperationalEvent) -> None: ...
    def list_recent(self, limit: int = 50) -> list[OperationalEvent]: ...
